// Copyright 2020 FastWeGo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

type Param struct {
	Name string
	Type string
}

type Api struct {
	Name        string
	Description string
	Request     string
	See         string
	FuncName    string
	GetParams   []Param
}

type ApiGroup struct {
	Name    string
	Apis    []Api
	Package string
}

var apiConfig = []ApiGroup{
	{
		Name:    `身份验证`,
		Package: `auth`,
		Apis: []Api{
			{
				Name:        "获取用户userid",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/getuserinfo?access_token=access_token&code=code",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/clotub",
				FuncName:    "GetUserInfo",
				GetParams: []Param{
					{Name: `code`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `通讯录管理`,
		Package: `contact`,
		Apis: []Api{
			{
				Name:        "获取通讯录权限范围",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/auth/scopes?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vt6v7m",
				FuncName:    "Scopes",
			},
		},
	},
	{
		Name:    `通讯录/用户管理`,
		Package: `contact/user`,
		Apis: []Api{

			{
				Name:        "创建用户",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/user/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "Create",
			},
			{
				Name:        "更新用户",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/user/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "Update",
			},
			{
				Name:        "删除用户",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/delete?access_token=ACCESS_TOKENuserid=zhangsan",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "Delete",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "获取用户详情",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/get?access_token=ACCESS_TOKENuserid=zhangsan",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "Get",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "获取部门用户userid列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/getDeptMember?access_token=ACCESS_TOKENdeptId=1",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "GetDeptMember",
				GetParams: []Param{
					{Name: `deptId`, Type: `string`},
				},
			},
			{
				Name:        "获取部门用户",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/simplelist?access_token=ACCESS_TOKENdepartment_id=1",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "SimpleList",
				GetParams: []Param{
					{Name: `department_id`, Type: `string`},
				},
			},
			{
				Name:        "获取部门用户详情",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/listbypage?access_token=ACCESS_TOKENdepartment_id=1",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "ListByPage",
				GetParams: []Param{
					{Name: `department_id`, Type: `string`},
				},
			},
			{
				Name:        "获取管理员列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/get_admin?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "GetAdmin",
			},
			{
				Name:        "获取管理员通讯录权限范围",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/user/get_admin_scope?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "GetAdminScope",
			},
			{
				Name:        "根据unionid获取userid",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/getUseridByUnionid?access_token=ACCESS_TOKENunionid=xxx",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "GetUseridByUnionid",
				GetParams: []Param{
					{Name: `unionid`, Type: `string`},
				},
			},
			{
				Name:        "根据手机号获取userid",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/get_by_mobile?access_token=ACCESS_TOKENmobile=1xxxxxxxxxx",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "GetByMobile",
				GetParams: []Param{
					{Name: `mobile`, Type: `string`},
				},
			},
			{
				Name:        "获取企业员工人数",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/user/get_org_user_count?access_token=ACCESS_TOKENonlyActive=0",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "GetOrgUserCount",
				GetParams: []Param{
					{Name: `onlyActive`, Type: `string`},
				},
			},
			{
				Name:        "未登录钉钉的员工列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/inactive/user/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ege851",
				FuncName:    "InactiveUserGet",
			},
		},
	},
	{
		Name:    `通讯录/部门管理`,
		Package: `contact/department`,
		Apis: []Api{

			{
				Name:        "创建部门",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/department/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "Create",
			},
			{
				Name:        "更新部门",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/department/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "Update",
			},
			{
				Name:        "删除部门",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/department/delete?access_token=ACCESS_TOKENid=ID",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "Delete",
				GetParams: []Param{
					{Name: `id`, Type: `string`},
				},
			},
			{
				Name:        "获取子部门ID列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/department/list_ids?access_token=ACCESS_TOKENid=ID",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "ListIds",
				GetParams: []Param{
					{Name: `id`, Type: `string`},
				},
			},
			{
				Name:        "获取部门列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/department/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "List",
			},
			{
				Name:        "获取部门详情",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/department/get?access_token=ACCESS_TOKENid=123",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "Get",
				GetParams: []Param{
					{Name: `id`, Type: `string`},
				},
			},
			{
				Name:        "查询部门的所有上级父部门路径",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/department/list_parent_depts_by_dept?access_token=ACCESS_TOKENid=ID",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "ListParentDeptsByDept",
				GetParams: []Param{
					{Name: `id`, Type: `string`},
				},
			},
			{
				Name:        "查询指定用户的所有上级父部门路径",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/department/list_parent_depts?access_token=ACCESS_TOKENuserId=USERID",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dubakq",
				FuncName:    "ListParentDepts",
				GetParams: []Param{
					{Name: `userId`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `通讯录/角色管理`,
		Package: `contact/role`,
		Apis: []Api{

			{
				Name:        "获取角色列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "List",
			},
			{
				Name:        "获取角色下的员工列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/simplelist?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "SimpleList",
			},
			{
				Name:        "获取角色组",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/getrolegroup?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "GetRoleGroup",
			},
			{
				Name:        "获取角色详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/getrole?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "GetRole",
			},
			{
				Name:        "创建角色",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/role/add_role?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "AddRole",
			},
			{
				Name:        "更新角色",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/role/update_role?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "UpdateRole",
			},
			{
				Name:        "删除角色",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/deleterole?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "DeleteRole",
			},
			{
				Name:        "创建角色组",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/role/add_role_group?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "AddRoleGroup",
			},
			{
				Name:        "批量增加员工角色",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/addrolesforemps?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "AddRolesForEmps",
			},
			{
				Name:        "批量删除员工角色",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/removerolesforemps?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "RemoveRolesForEmps",
			},
			{
				Name:        "设定角色成员管理范围",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/role/scope/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dnu5l1",
				FuncName:    "ScopeUpdate",
			},
		},
	},
	{
		Name:    `通讯录/外部联系人管理`,
		Package: `contact/extcontact`,
		Apis: []Api{

			{
				Name:        "获取外部联系人标签列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/extcontact/listlabelgroups?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nb93oa",
				FuncName:    "ListLabelGroups",
			},
			{
				Name:        "获取外部联系人列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/extcontact/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nb93oa",
				FuncName:    "List",
			},
			{
				Name:        "获取外部联系人详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/extcontact/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nb93oa",
				FuncName:    "Get",
			},
			{
				Name:        "添加外部联系人",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/extcontact/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nb93oa",
				FuncName:    "Create",
			},
			{
				Name:        "更新外部联系人",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/extcontact/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nb93oa",
				FuncName:    "Update",
			},
			{
				Name:        "删除外部联系人",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/extcontact/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nb93oa",
				FuncName:    "Delete",
			},
		},
	},
	{
		Name:    `家校通讯录`,
		Package: `contact/edu`,
		Apis: []Api{

			{
				Name:        "获取部门列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/edu/dept/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zaypkk",
				FuncName:    "DeptList",
			},
			{
				Name:        "获取部门详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/edu/dept/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zaypkk",
				FuncName:    "DeptGet",
			},
			{
				Name:        "部门完整示例",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/edu/user/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zaypkk",
				FuncName:    "UserList",
			},
			{
				Name:        "获取人员详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/edu/user/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zaypkk",
				FuncName:    "UserGet",
			},
			{
				Name:        "获取人员关系列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/edu/user/relation/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zaypkk",
				FuncName:    "UserRelationList",
			},
			{
				Name:        "获取人员关系详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/edu/user/relation/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zaypkk",
				FuncName:    "UserRelationGet",
			},
		},
	},
	{
		Name:    `群会话管理`,
		Package: `chat`,
		Apis: []Api{

			{
				Name:        "创建会话",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/chat/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/fg9dze",
				FuncName:    "Create",
			},
			{
				Name:        "修改会话",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/chat/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/lewq17",
				FuncName:    "Update",
			},
			{
				Name:        "获取会话",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/chat/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kruhy0",
				FuncName:    "Get",
			},
			{
				Name:        "设置群管理员",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/chat/subadmin/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/leqbe8",
				FuncName:    "SubadminUpdate",
			},
			{
				Name:        "设置禁止群成员私聊",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/chat/member/friendswitch/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zb74qt",
				FuncName:    "FriendSwitchUpdate",
			},
		},
	},
	{
		Name:    `消息通知`,
		Package: `message`,
		Apis: []Api{

			{
				Name:        "查询工作通知消息的发送进度",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/message/corpconversation/asyncsend_v2?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pgoxpy",
				FuncName:    "AsyncsendV2",
			},
			{
				Name:        "查询工作通知消息的发送进度",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/message/corpconversation/getsendprogress?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pgoxpy",
				FuncName:    "GetSendProgress",
			},
			{
				Name:        "查询工作通知消息的发送结果",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/message/corpconversation/getsendresult?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pgoxpy",
				FuncName:    "GetSendResult",
			},
			{
				Name:        "工作通知消息撤回",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/message/corpconversation/recall?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pgoxpy",
				FuncName:    "Recall",
			},
			{
				Name:        "发送消息到企业群",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/chat/send?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/isu6nk",
				FuncName:    "Send",
			},
			{
				Name:        "查询群消息已读人员列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/chat/getReadList?access_token=ACCESS_TOKENmessageId=MESSAGEIDcursor=CURSORsize=SIZE",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/isu6nk",
				FuncName:    "GetReadList",
				GetParams: []Param{
					{Name: `messageId`, Type: `string`},
					{Name: `cursor`, Type: `string`},
					{Name: `size`, Type: `string`},
				},
			},
			{
				Name:        "发送普通消息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/message/send_to_conversation?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pm0m06",
				FuncName:    "SendToConversation",
			},
		},
	},
	{
		Name:    `智能工作流/官方`,
		Package: `process`,
		Apis: []Api{

			{
				Name:        "发起审批实例",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/processinstance/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/cmct1a",
				FuncName:    "Create",
			},
			{
				Name:        "批量获取审批实例id",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/processinstance/listids?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/hh8lx5",
				FuncName:    "ListIds",
			},
			{
				Name:        "获取审批实例详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/processinstance/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xgqkvx",
				FuncName:    "Get",
			},
			{
				Name:        "获取用户待审批数量",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/gettodonum?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ui5305",
				FuncName:    "GetTodoNum",
			},
			{
				Name:        "获取用户可见的审批模板",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/listbyuserid?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/tcwmha",
				FuncName:    "ListByUserId",
			},
			{
				Name:        "获取审批钉盘空间信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/processinstance/cspace/info?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xq6ml3",
				FuncName:    "CspaceInfo",
			},
			{
				Name:        "预览审批附件",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/processinstance/cspace/preview?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/sg687u",
				FuncName:    "CspacePreview",
			},
		},
	},
	{
		Name:    `智能工作流/自有`,
		Package: `process/custom`,
		Apis: []Api{

			{
				Name:        "创建或更新模板",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/save?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xcgg03",
				FuncName:    "Save",
			},
			{
				Name:        "获取模板code",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/get_by_name?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uts09n",
				FuncName:    "GetByName",
			},
			{
				Name:        "删除模板",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ilni1r",
				FuncName:    "Delete",
			},
			{
				Name:        "创建实例",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xfg2g9",
				FuncName:    "Create",
			},
			{
				Name:        "更新实例状态",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/as4xlh",
				FuncName:    "Update",
			},
			{
				Name:        "批量更新实例状态",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/batchupdate?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/as4xlh",
				FuncName:    "BatchUpdate",
			},
			{
				Name:        "创建待办事项",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/task/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/rbe7gs",
				FuncName:    "TaskCreate",
			},
			{
				Name:        "更新待办状态",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/task/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/riycru",
				FuncName:    "TaskUpdate",
			},
			{
				Name:        "批量取消待办",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/taskgroup/cancel?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/yaiekm",
				FuncName:    "TaskGroupCancel",
			},
			{
				Name:        "查询用户待办列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/process/workrecord/task/query?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/riueql",
				FuncName:    "TaskQuery",
			},
		},
	},
	{
		Name:    `待办任务`,
		Package: `todo`,
		Apis: []Api{

			{
				Name:        "发起待办",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/workrecord/add?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/gpmpiq",
				FuncName:    "Add",
			},
			{
				Name:        "更新待办",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/workrecord/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/cxls8y",
				FuncName:    "Update",
			},
			{
				Name:        "获取用户待办事项",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/workrecord/getbyuserid?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/neevhm",
				FuncName:    "GetByUserId",
			},
		},
	},
	{
		Name:    `考勤`,
		Package: `attendance`,
		Apis: []Api{

			{
				Name:        "查询企业考勤排班详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/listschedule?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ufc8dl",
				FuncName:    "ListSchedule",
			},
			{
				Name:        "查询成员排班信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/schedule/listbyday?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ufc8dl",
				FuncName:    "ListByDay",
			},
			{
				Name:        "批量查询成员排班信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/schedule/listbyusers?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ufc8dl",
				FuncName:    "ListByUsers",
			},
			{
				Name:        "排班制考勤组排班",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/schedule/async?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ufc8dl",
				FuncName:    "ScheduleAsync",
			},
			{
				Name:        "查询排班打卡结果",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/schedule/result/listbyids?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ufc8dl",
				FuncName:    "ListByIds",
			},
			{
				Name:        "批量查询班次摘要信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/shift/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pmug9c",
				FuncName:    "AttendanceShiftList",
			},
			{
				Name:        "查询班次详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/shift/query?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pmug9c",
				FuncName:    "AttendanceShiftQuery",
			},
			{
				Name:        "按名称搜索班次",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/shift/search?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pmug9c",
				FuncName:    "AttendanceShiftSearch",
			},
			{
				Name:        "获取打卡详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/attendance/listRecord?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/potcn9",
				FuncName:    "ListRecord",
			},
			{
				Name:        "获取打卡结果",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/attendance/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ul33mm",
				FuncName:    "AttendanceList",
			},
			{
				Name:        "查询请假状态",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/getleavestatus?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/chhwzv",
				FuncName:    "GetLeaveStatus",
			},
			{
				Name:        "批量获取企业考勤组详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/getsimplegroups?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ksk4o2",
				FuncName:    "GetSimpleGroups",
			},
			{
				Name:        "获取考勤组摘要",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/minimalism/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ksk4o2",
				FuncName:    "AttendanceGroupMinimalismList",
			},
			{
				Name:        "搜索考勤组摘要",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/search?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ksk4o2",
				FuncName:    "AttendanceGroupSearch",
			},
			{
				Name:        "获取考勤组详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/query?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ksk4o2",
				FuncName:    "AttendanceGroupQuery",
			},
			{
				Name:        "获取用户考勤组",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/getusergroup?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uvt47u",
				FuncName:    "GetUserGroup",
			},
			{
				Name:        "获取考勤组员工id",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/memberusers/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uvt47u",
				FuncName:    "AttendanceGroupMemberUsersList",
			},
			{
				Name:        "考勤组成员校验",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/member/listbyids?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uvt47u",
				FuncName:    "AttendanceGroupMemberListbyids",
			},
			{
				Name:        "考勤组成员更新",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/member/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uvt47u",
				FuncName:    "AttendanceGroupMemberUpdate",
			},
			{
				Name:        "获取考勤组成员",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/group/member/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uvt47u",
				FuncName:    "AttendanceGroupMemberList",
			},
			{
				Name:        "是否启用智能统计报表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/isopensmartreport?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vg7ned",
				FuncName:    "IsOpenSmartReport",
			},
			{
				Name:        "获取报表列定义",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/getattcolumns?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vg7ned",
				FuncName:    "GetAttColumns",
			},
			{
				Name:        "获取报表列值",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/getcolumnval?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vg7ned",
				FuncName:    "GetColumnVal",
			},
			{
				Name:        "获取报表假期数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/attendance/getleavetimebynames?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vg7ned",
				FuncName:    "GetLeaveTimeByNames",
			},
		},
	},
	{
		Name:    `智能人事`,
		Package: `hr`,
		Apis: []Api{

			{
				Name:        "获取员工花名册字段信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/rikq4i",
				FuncName:    "EmployeeList",
			},
			{
				Name:        "更新员工花名册",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/aw6wuy",
				FuncName:    "EmployeeUpdate",
			},
			{
				Name:        "查询花名册元数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/field/grouplist?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/beo741",
				FuncName:    "EmployeeFieldGrouplist",
			},
			{
				Name:        "查询企业待入职员工列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/querypreentry?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/yv3mcy",
				FuncName:    "QueryPreentry",
			},
			{
				Name:        "查询企业在职员工列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/queryonjob?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/rafx8t",
				FuncName:    "Queryonjob",
			},
			{
				Name:        "查询企业离职员工列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/querydimission?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/oe0nlx",
				FuncName:    "QueryDimission",
			},
			{
				Name:        "获取离职员工离职信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/listdimission?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/fbtugn",
				FuncName:    "ListDimission",
			},
			{
				Name:        "添加企业待入职员工",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/smartwork/hrm/employee/addpreentry?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/dhlu4d",
				FuncName:    "AddPreentry",
			},
		},
	},
	{
		Name:    `日志`,
		Package: `report`,
		Apis: []Api{

			{
				Name:        "获取企业用户日志数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/yknhmg",
				FuncName:    "List",
			},
			{
				Name:        "获取用户发送日志概要信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/simplelist?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/cp4mxh",
				FuncName:    "Simplelist",
			},
			{
				Name:        "获取日志统计数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/statistics?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/lhlow3",
				FuncName:    "Statistics",
			},
			{
				Name:        "获取日志相关人员列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/statistics/listbytype?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/qga9wa",
				FuncName:    "ListByType",
			},
			{
				Name:        "获取日志接收人员列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/receiver/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/el6lgx",
				FuncName:    "ReportReceiverList",
			},
			{
				Name:        "获取日志评论详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/comment/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pmyeg8",
				FuncName:    "ReportCommentList",
			},
			{
				Name:        "获取用户日志未读数",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/getunreadcount?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/yz2vbx",
				FuncName:    "GetUnreadCount",
			},
			{
				Name:        "获取用户可见的日志模板",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/report/template/listbyuserid?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/lbt9b4",
				FuncName:    "ListByUserId",
			},
		},
	},
	{
		Name:    `日程`,
		Package: `calendar`,
		Apis: []Api{

			{
				Name:        "创建日程",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/calendar/v2/event/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/iqel76",
				FuncName:    "Create",
			},
			{
				Name:        "修改日程",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/calendar/v2/event/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zg9qoo",
				FuncName:    "Update",
			},
			{
				Name:        "取消日程",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/calendar/v2/event/cancel?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/nf4c9z",
				FuncName:    "Cancel",
			},
			{
				Name:        "新增/删除参会人",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/calendar/v2/attendee/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/atuhpy",
				FuncName:    "AttendeeUpdate",
			},
		},
	},
	{
		Name:    `签到`,
		Package: `checkin`,
		Apis: []Api{

			{
				Name:        "获取部门用户签到记录",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/checkin/record?access_token=ACCESS_TOKENdepartment_id=1start_time=1467707227000end_time=1467707240000offset=0size=100order=asc",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uyr2ah",
				FuncName:    "Record",
				GetParams: []Param{
					{Name: `department_id`, Type: `string`},
					{Name: `start_time`, Type: `string`},
					{Name: `end_time`, Type: `string`},
					{Name: `offset`, Type: `string`},
					{Name: `size`, Type: `string`},
					{Name: `order`, Type: `string`},
				},
			},
			{
				Name:        "获取用户签到记录",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/checkin/record/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/uyr2ah",
				FuncName:    "Get",
			},
		},
	},
	{
		Name:    `公告`,
		Package: `blackboard`,
		Apis: []Api{

			{
				Name:        "获取用户可查看的公告",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/listtopten?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/knmd16",
				FuncName:    "ListTop10",
			},
			{
				Name:        "获取公告分类列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/category/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/lfaanr",
				FuncName:    "CategoryList",
			},
			{
				Name:        "获取公告id列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/listids?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/cgu5xo",
				FuncName:    "ListIds",
			},
			{
				Name:        "创建公告",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/create?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/owbsbu",
				FuncName:    "Create",
			},
			{
				Name:        "更新公告",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pv3zqa",
				FuncName:    "Update",
			},
			{
				Name:        "删除公告",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zgmbq9",
				FuncName:    "Delete",
			},
			{
				Name:        "获取公告详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/blackboard/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xxz4hb",
				FuncName:    "Get",
			},
		},
	},
	{
		Name:    `钉钉运动`,
		Package: `health/stepinfo`,
		Apis: []Api{

			{
				Name:        "获取用户钉钉运动开启状态",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/health/stepinfo/getuserstatus?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/emdh5f",
				FuncName:    "GetUserStatus",
			},
			{
				Name:        "获取个人或部门的钉钉运动数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/health/stepinfo/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/emdh5f",
				FuncName:    "List",
			},
			{
				Name:        "批量获取钉钉运动数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/health/stepinfo/listbyuserid?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/emdh5f",
				FuncName:    "ListByUserid",
			},
		},
	},
	{
		Name:    `应用管理`,
		Package: `microapp`,
		Apis: []Api{

			{
				Name:        "获取应用列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/microapp/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zc304p",
				FuncName:    "List",
			},
			{
				Name:        "获取员工可见的应用列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/microapp/list_by_userid?access_token=ACCESS_TOKENuserid=manager",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zc304p",
				FuncName:    "ListByUserid",
				GetParams: []Param{
					{Name: `userid`, Type: `string`},
				},
			},
			{
				Name:        "获取应用的可见范围",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/microapp/visible_scopes?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zc304p",
				FuncName:    "VisibleScopes",
			},
			{
				Name:        "设置应用的可见范围",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/microapp/set_visible_scopes?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/zc304p",
				FuncName:    "SetVisibleScopes",
			},
		},
	},
	{
		Name:    `文件存储`,
		Package: `cspace`,
		Apis: []Api{

			{
				Name:        "上传媒体文件",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/media/upload?access_token=ACCESS_TOKENtype=TYPE",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/bcmg0i",
				FuncName:    "Upload",
				GetParams: []Param{
					{Name: `type`, Type: `string`},
				},
			},

			{
				Name:        "发送钉盘文件给指定用户",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/cspace/add_to_single_chat?access_token=ACCESS_TOKENagent_id=AGENT_IDuserid=USERIDmedia_id=MEDIA_IDfile_name=FILE_NAME",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "AddToSingleChat",
				GetParams: []Param{
					{Name: `agent_id`, Type: `string`},
					{Name: `userid`, Type: `string`},
					{Name: `media_id`, Type: `string`},
					{Name: `file_name`, Type: `string`},
				},
			},
			{
				Name:        "新增文件到用户自定义空间",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/cspace/add?access_token=ACCESS_TOKENagent_id=AGENT_IDcode=CODEmedia_id=MEDIA_IDspace_id=SPACE_IDfolder_id=FOLDER_IDname=NAMEoverwrite=OVERWRITEpath=PATH",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "Add",
				GetParams: []Param{
					{Name: `space_id`, Type: `string`},
					{Name: `name`, Type: `string`},
					{Name: `overwrite`, Type: `string`},
					{Name: `agent_id`, Type: `string`},
					{Name: `code`, Type: `string`},
					{Name: `media_id`, Type: `string`},
					{Name: `folder_id`, Type: `string`},
					{Name: `path`, Type: `string`},
				},
			},
			{
				Name:        "获取企业下的自定义空间",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/cspace/get_custom_space?access_token=ACCESS_TOKENdomain=DOMAINagent_id=AGENT_ID",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "GetCustomSpace",
				GetParams: []Param{
					{Name: `domain`, Type: `string`},
					{Name: `agent_id`, Type: `string`},
				},
			},
			{
				Name:        "获取应用自定义空间使用详情",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/cspace/used_info?access_token=ACCESS_TOKENagent_id=AGENT_IDdomain=DOMAIN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "UsedInfo",
				GetParams: []Param{
					{Name: `agent_id`, Type: `string`},
					{Name: `domain`, Type: `string`},
				},
			},
			{
				Name:        "授权用户访问企业自定义空间",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/cspace/grant_custom_space?access_token=ACCESS_TOKENdomain=DOMAINagent_id=AGENT_IDtype=TYPEuserid=USERIDpath=PATHfileids=FILEIDSduration=DURATION",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "GrantCustomSpace",
				GetParams: []Param{
					{Name: `domain`, Type: `string`},
					{Name: `agent_id`, Type: `string`},
					{Name: `type`, Type: `string`},
					{Name: `userid`, Type: `string`},
					{Name: `path`, Type: `string`},
					{Name: `fileids`, Type: `string`},
					{Name: `duration`, Type: `string`},
				},
			},
			{
				Name:        "单步上传文件",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/file/upload/single?access_token=ACCESS_TOKENagent_id=AGENT_IDfile_size=FILE_SIZE",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "UploadSingle",
				GetParams: []Param{
					{Name: `agent_id`, Type: `string`},
					{Name: `file_size`, Type: `string`},
				},
			},
			{
				Name: "开启/提交文件上传事务",
				Description: `开启分块上传事务
文件分块上传第一步，开启上传事务，该接口返回upload_id，钉盘服务器以upload_id唯一标识一个上传任务。分块最小需大于100KB，最大不超过8M，最多支持10000块。

注意：浏览器可能会转义某些字符导致请求失败，调试时请使用curl或者代码模拟请求。`,
				Request:  "GET https://oapi.dingtalk.com/file/upload/transaction?access_token=ACCESS_TOKENagent_id=AGENT_IDfile_size=FILE_SIZEchunk_numbers=CHUNK_NUMBERS",
				See:      "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName: "Transaction",
				GetParams: []Param{
					{Name: `agent_id`, Type: `string`},
					{Name: `file_size`, Type: `string`},
					{Name: `chunk_numbers`, Type: `string`},
				},
			},
			{
				Name:        "上传文件块",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/file/upload/chunk?access_token=ACCESS_TOKENagent_id=AGENT_IDupload_id=UPLOAD_IDchunk_sequence=CHUNK_SEQUENCE",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/wk3krc",
				FuncName:    "UploadChunk",
				GetParams: []Param{
					{Name: `agent_id`, Type: `string`},
					{Name: `upload_id`, Type: `string`},
					{Name: `chunk_sequence`, Type: `string`},
				},
			},
		},
	},
	{
		Name:    `AI`,
		Package: `ai`,
		Apis: []Api{
			{
				Name:        "文本翻译",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/ai/mt/translate?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/cvcp9r",
				FuncName:    "Translate",
			},
			{
				Name:        "OCR文字识别",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/ocr/structured/recognize?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/so7gg5",
				FuncName:    "Recognize",
			},
		},
	},
	{
		Name:    `专属钉钉/数据统计`,
		Package: `private/datav`,
		Apis: []Api{

			{
				Name:        "使用说明",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/videolive/get_access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "GetAccessToken",
			},
			{
				Name:        "获取企业视频直播统计列表（部门维度）",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/dept/videolive/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavDeptVideoliveList",
			},
			{
				Name:        "获取企业视频直播情况",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/videolive/detail/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavVideoliveDetailList",
			},
			{
				Name:        "获取企业视频直播观看人员明细列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/videolive/viewer/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavVideoliveViewerList",
			},
			{
				Name:        "获取企业各类群组创建情况",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/group/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavGroupGet",
			},
			{
				Name:        "获取企业某天的视频会议统计数据2.0",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/v2/datav/videoconf/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacV2DatavVideoconfGet",
			},

			{
				Name:        "获取企业某天的所有部门视频会议统计数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/dept/videoconf/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavDeptVideoconfList",
			},
			{
				Name:        "获取企业视频会议明细列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/videoconf/detail/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavVideoconfDetailList",
			},
			{
				Name:        "获取企业某天的电话会议数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/telconf/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavTelconfGet",
			},
			{
				Name:        "获取企业某天的所有部门电话会议统计列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/dept/telconf/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavDeptTelconfList",
			},
			{
				Name:        "获取企业电话会议明细列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/telconf/detail/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavTelconfDetailList",
			},
			{
				Name:        "获取企业聊天数据",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/chat/summary/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavChatSummaryGet",
			},
			{
				Name:        "获取企业应用访问情况",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/microapp/detail/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavMicroappDetailList",
			},
			{
				Name:        "统计企业活跃用户",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/dau/summary/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavDauSummaryGet",
			},
			{
				Name:        "企业活跃用户统计列表（部门维度）",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/dept/dau/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavDeptDauList",
			},
			{
				Name:        "企业通讯录未激活用户列表",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/kac/datav/inactivated/user/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/vbywnn",
				FuncName:    "KacDatavInactivatedUserList",
			},
		},
	},
	{
		Name:    `专属钉钉/互动服务窗`,
		Package: `private/service`,
		Apis: []Api{

			{
				Name:        "新增服务号",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/serviceaccount/add?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/elc75y",
				FuncName:    "ServiceaccountAdd",
			},
			{
				Name:        "查询服务号详情",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/serviceaccount/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/elc75y",
				FuncName:    "ServiceaccountGet",
			},
			{
				Name:        "更新服务号",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/serviceaccount/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/elc75y",
				FuncName:    "ServiceaccountUpdate",
			},
			{
				Name:        "查询服务号列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/serviceaccount/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/elc75y",
				FuncName:    "ServiceaccountList",
			},
			{
				Name:        "新增文章",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/article/add?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ngs3sp",
				FuncName:    "MaterialArticleAdd",
			},
			{
				Name:        "获取文章详情",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/material/article/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ngs3sp",
				FuncName:    "MaterialArticleGet",
			},
			{
				Name:        "更新文章",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/article/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ngs3sp",
				FuncName:    "MaterialArticleUpdate",
			},
			{
				Name:        "发布文章",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/article/publish?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ngs3sp",
				FuncName:    "MaterialArticlePublish",
			},
			{
				Name:        "查询文章列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/material/article/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ngs3sp",
				FuncName:    "MaterialArticleList",
			},
			{
				Name:        "删除文章",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/article/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ngs3sp",
				FuncName:    "MaterialArticleDelete",
			},
			{
				Name:        "新增消息卡片",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/news/add?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xwidee",
				FuncName:    "MaterialNewsAdd",
			},
			{
				Name:        "获取消息卡片详情",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/material/news/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xwidee",
				FuncName:    "MaterialNewsGet",
			},
			{
				Name:        "更新消息卡片",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/news/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xwidee",
				FuncName:    "MaterialNewsUpdate",
			},
			{
				Name:        "查询消息卡片列表",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/material/news/list?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xwidee",
				FuncName:    "MaterialNewsList",
			},
			{
				Name:        "删除消息卡片 ",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/material/news/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/xwidee",
				FuncName:    "MaterialNewsDelete",
			},
			{
				Name:        "批量发消息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/message/mass/send?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/aidmta",
				FuncName:    "MessageMassSend",
			},
			{
				Name:        "消息撤回",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/message/mass/recall?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/aidmta",
				FuncName:    "MessageMassRecall",
			},
			{
				Name:        "更新菜单",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/serviceaccount/menu/update?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ux6nqr",
				FuncName:    "ServiceaccountMenuUpdate",
			},
			{
				Name:        "获取菜单",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/topapi/serviceaccount/menu/get?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/ux6nqr",
				FuncName:    "ServiceaccountMenuGet",
			},
		},
	},
	{
		Name:    `阿里商旅`,
		Package: `alitrip`,
		Apis: []Api{

			{
				Name:        "机票城市搜索",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/flight/city/suggest?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kg5g2g",
				FuncName:    "BtripFlightCitySuggest",
			},
			{
				Name:        "火车票城市搜索",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/train/city/suggest?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kg5g2g",
				FuncName:    "BtripTrainCitySuggest",
			},
			{
				Name:        "新建成本中心",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/new?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "BtripCostCenterNew",
			},
			{
				Name:        "修改成本中心",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/modify?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "ABtripCostCenterModify",
			},
			{
				Name:        "查询成本中心",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/query?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "BtripCostCenterQuery",
			},
			{
				Name:        "删除成本中心",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "BtripCostCenterDelete",
			},
			{
				Name:        "设置成本中心人员信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/entity/set?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "BtripCostCenterEntitySet",
			},
			{
				Name:        "删除成本中心人员信息",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/entity/delete?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "BtripCostCenterEntityDelete",
			},
			{
				Name:        "商旅成本中心转换为外部成本中心",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/topapi/alitrip/btrip/cost/center/transfer?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/kaklal",
				FuncName:    "BtripCostCenterTransfer",
			},
		},
	},
	{
		Name:    `业务事件回调`,
		Package: `callback`,
		Apis: []Api{

			{
				Name:        "注册业务事件回调接口",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/call_back/register_call_back?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pwz3r5",
				FuncName:    "RegisterCallBack",
			},
			{
				Name:        "测试回调URL",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/call_back/get_call_back?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pwz3r5",
				FuncName:    "GetCallBack",
			},
			{
				Name:        "更新事件回调接口",
				Description: "",
				Request:     "POST https://oapi.dingtalk.com/call_back/update_call_back?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pwz3r5",
				FuncName:    "UpdateCallBack",
			},
			{
				Name:        "删除事件回调接口",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/call_back/delete_call_back?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pwz3r5",
				FuncName:    "DeleteCallBack",
			},
			{
				Name:        "获取回调失败的结果",
				Description: "",
				Request:     "GET https://oapi.dingtalk.com/call_back/get_call_back_failed_result?access_token=ACCESS_TOKEN",
				See:         "https://ding-doc.dingtalk.com/doc#/serverapi2/pwz3r5",
				FuncName:    "GetCallBackFailedResult",
			},
		},
	},
}
